### ISSUE TITLE
--version flag does not work

### ISSUE THREAD

**Issue by JWDebler** [LuoGroup2023/DeChat#1]
Hi,

the `--version`  flag does not seem to work.
I installed the current version (1.0.0) through conda and when I type

`dechat --version` I get:
`[ERROR] missing input: please specify a read file`

If I add an input file and output prefix followed by `--version` it goes straight to read correction.

Cheers,
Johannes

**Comment by LuoGroup2023** [comment]
Hi Johannes,

Thank you very much for pointing out the issue. The latest uploaded code has fixed the problem! The fix in Conda will also be completed within a few days. You can now clone the latest code to test it.

Sincerely,

Yichen
