### ISSUE TITLE
Multiple files accepted in -i and -d?

### ISSUE THREAD

**Issue by melop** [LuoGroup2023/DeChat#6]
Hi, I am just wondering because I have read1 and read2 NGS files in two separate fq.gz files, must I first concatenate them together or can dechat take multiple files with -d? How about -i?

**Comment by LuoGroup2023** [comment]
> Hi, I am just wondering because I have read1 and read2 NGS files in two separate fq.gz files, must I first concatenate them together or can dechat take multiple files with -d? How about -i?

Hi，

You can use the cat command to merge NGS files, then use -d to generate the dbg.
