### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by bpanda-dev** [LuoGroup2023/DeChat#7]
Hi, 
Thanks for this wonderful error correction tool. The error correction is giving very good results for ONT long R10 simplex reads. 
I have two bugs to report for the latest v1.0.1 release installed from conda.
1. Printing version `dechat -v` or `dechat --version` prints only `DeChat version:` without showing the version info.
2. The `max_read_len` printed while execution is double of the actual value.

Also, have you compared the performance of DeChat with HERRO?
Thank You.

**Comment by LuoGroup2023** [comment]
> Hi, Thanks for this wonderful error correction tool. The error correction is giving very good results for ONT long R10 simplex reads. I have two bugs to report for the latest v1.0.1 release installed from conda.
> 
> 1. Printing version `dechat -v` or `dechat --version` prints only `DeChat version:` without showing the version info.
> 2. The `max_read_len` printed while execution is double of the actual value.
> 
> Also, have you compared the performance of DeChat with HERRO? Thank You.
Hi,

Thank you very much for pointing out the issue. The conda version has not yet been updated to v1.0.1, so the version error still exists with the conda installation. As you mentioned, the output of max_read_len specifies its size to be about 1.4 times the length of the longest sequence. Unfortunately, we have not yet compared it with the HERRO software.

Best regards.
